version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=card_marketplace
      - DB_HOST=db
      - JWT_SECRET=askfhajfhafsasfajsfkajs
    volumes:
      - ./backend:/app-backend
    container_name: card_markeplace_backend
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=card_marketplace
    restart: always
